name: Read Hello File

on:
  push:
    branches:
      - main

jobs:
  read-hello-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print hello.txt contents
        run: cat hello.txt
